"""empty message

Revision ID: 516693809ede
Revises: 
Create Date: 2022-01-25 19:38:13.768086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516693809ede'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('addr1', sa.String(), nullable=True))
    op.add_column('application', sa.Column('addr2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'addr2')
    op.drop_column('application', 'addr1')
    # ### end Alembic commands ###
