"""added application-specific notes

Revision ID: f46d13f88c7c
Revises: 516693809ede
Create Date: 2022-01-27 20:27:56.174447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46d13f88c7c'
down_revision = '516693809ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'notes')
    # ### end Alembic commands ###
